[package]
name = "terrain-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
metis-core = { git = "https://github.com/giodl73-repo/METIS-CORE.git" }
scenarium = { git = "https://github.com/giodl73-repo/SCENARIUM.git", rev = "f731ad4f99cc57479eafce6b68ea6521160c6853" }
